require('core.packer')
-- require('config.specs')
require('config.bufferline')
require('config.lualine')
require('config.nvimtree')
require('config.gitsigns')
require('config.tmux')
require('config.blankline')
require('config.treesitter')

